# Override default hydra config
# Don't use any interpolations here - keep it simple

defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# Output directory for hydra
run:
  dir: logs/train/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}

sweep:
  dir: logs/train/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}