# configs/extras/default.yaml
defaults: []

# Print config tree before training
print_config: true

# Ignore warnings
ignore_warnings: false

# Force debug friendly configuration
# Use this to debug issues in training
enforce_tags: true

# Pretty print using Rich library
# Set to false to disable
print_config_tree: true