# https://wandb.ai

wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  save_dir: "${paths.output_dir}"
  offline: False # set True to store all logs only locally
  id: null # pass correct id to resume experiment!
  anonymous: null # enable anonymous logging
  project: "spatial-mamba-segmentation"
  log_model: True # upload lightning ckpts
  prefix: "" # a string to put at the beginning of metric keys
  entity: null # set to name of your wandb team or just remove it
  tags: ${tags}
  group: ""
  name: ${name}