defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml

# Pass callbacks to trainer
# NOTE: "+" means append to the list, don't override
model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/dice"
  mode: "max"
  save_top_k: 3
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: "val/dice"
  patience: 15
  mode: "max"

model_summary:
  _target_: lightning.pytorch.callbacks.ModelSummary
  max_depth: -1

rich_progress_bar:
  _target_: lightning.pytorch.callbacks.RichProgressBar