# @package _global_

defaults:
  - _self_
  - data: isic2017 # choose datamodule with `test_dataloader()` for evaluation
  - model: spatial_mamba_unet
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["eval", "spatial-mamba", "skin-lesion"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
