# @package _global_

defaults:
  - _self_
  - data: isic2017
  - model: spatial_mamba_unet
  - callbacks: default
  - logger: wandb
  - trainer: default
  - paths: default
  - hydra: default

  - experiment: null
  - optional local: default
  - debug: null

task_name: train

tags: ["spatial-mamba", "skin-lesion", "segmentation"]

train: true
test: true

seed: 42

name: null